baseURL = ""
languageCode = "en-us"
title = "MIT OpenCourseWare"

# Make sure errors with getJSON don't stop the build
ignoreErrors = ["error-remote-getjson"]

[module]
  [[module.imports]]
    path = "github.com/mitodl/ocw-hugo-themes/base-theme"
  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "data"
    target = "data"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "static"
    target = "static"
